"""DECLARED-PATH-EQUIVALENCE-001: bounded congruence receipt.

Research-only. A declared relation can identify distinct free paths in a quotient
without making the supplied paths identical or erasing the relation receipt.
"""
from itertools import product


def words(alphabet=("a", "b"), max_len=4):
    out = {""}
    for n in range(1, max_len + 1):
        out.update("".join(p) for p in product(alphabet, repeat=n))
    return out


def congruence_classes(lhs="aa", rhs="bb", max_len=4):
    universe = words(max_len=max_len)
    parent = {w: w for w in universe}

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(x, y):
        x, y = find(x), find(y)
        if x != y:
            parent[max(x, y)] = min(x, y)

    # Least bounded two-sided congruence generated by lhs ~ rhs.
    changed = True
    while changed:
        changed = False
        before = {w: find(w) for w in universe}
        for u in universe:
            for v in universe:
                x, y = u + lhs + v, u + rhs + v
                if x in universe and y in universe:
                    union(x, y)
        # close under already-known equivalences in all bounded contexts
        pairs = [(x, y) for x in universe for y in universe if find(x) == find(y)]
        for x, y in pairs:
            for u in universe:
                for v in universe:
                    uxv, uyv = u + x + v, u + y + v
                    if uxv in universe and uyv in universe:
                        union(uxv, uyv)
        after = {w: find(w) for w in universe}
        changed = before != after
    return {w: find(w) for w in sorted(universe)}


def receipt():
    classes = congruence_classes()
    p, q = "aa", "bb"
    return {
        "free_paths": [p, q],
        "free_paths_distinct": p != q,
        "declared_relation": {"lhs": p, "rhs": q, "name": "alpha"},
        "quotient_representatives": [classes[p], classes[q]],
        "same_quotient_class": classes[p] == classes[q],
        "relation_receipt_retained": True,
        "non_claims": [
            "path equivalence is not path identity",
            "rewrite witness is not occurrence",
            "quotient equality is not evidentiary equality",
            "algebraic congruence is not semantic authority",
        ],
    }
